apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - producer.yaml
  - consumer.yaml
  - streams.yaml

images:
  - name: clients-image
    newName: quay.io/strimzi-test-clients/test-clients
    newTag: latest-kafka-3.7.0
